name: EzBuy
main: com.cerrealic.ezbuy.EzBuy
version: 0.1.0a-pre8
api-version: 1.15
author: cerrealic
depend:
  - Vault
  - Essentials
commands:
  buy:
    description: Buy items from the server using your balance and the defined worth of the item.
    usage: /<command> <item>
    aliases: purchase
