name: EzBuy
description: Simple but effective Spigot plugin that adds a /buy command.
main: com.cerrealic.ezbuy.EzBuy
version: b0.3.6-SNAPSHOT
author: cerrealic
website: https://www.spigotmc.org/resources/ezbuy.77802/
depend:
  - Vault
  - Essentials
commands:
  buy:
    description: Buy items from the server using your balance and the defined worth of the item.
    usage: /<command> <item> <amount>
    aliases:
      - purchase
      - order
