name: EzBuy
description: Simple but effective Spigot plugin that adds a /buy command.
main: com.cerrealic.ezbuy.EzBuy
version: b0.4.0-SNAPSHOT
author: cerrealic
api-version: 1.15
website: https://www.spigotmc.org/resources/ezbuy.77802/
depend:
  - Vault
  - Essentials
commands:
  ezbuy:
    description: General command for setting config stuff.
    usage: /<command> <configkey> <value>
  buy:
    description: Buy items from the server using your balance and the defined worth of the item.
    usage: /<command> <item> <amount>
    aliases:
      - purchase
      - order
