name: ${project.name}
description: ${project.description}
main: com.cerrealic.ezbuy.EzBuy
version: ${project.version}
author: cerrealic
website: https://www.spigotmc.org/resources/ezbuy.77802/
depend:
  - Vault
  - Essentials
commands:
  buy:
    description: Buy items from the server using your balance and the defined worth of the item.
    usage: /<command> <item> <amount>
    aliases:
      - purchase
      - order
